# Generated by Django 4.1.3 on 2022-12-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_meal_options_alter_meal_plan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
    ]
