# Generated by Django 4.1.3 on 2022-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_meal_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
