# Generated by Django 4.1.3 on 2022-12-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_meal_meal_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='meal_img',
            new_name='meal_picture',
        ),
    ]
