# Generated by Django 4.1.3 on 2022-12-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_meal_img_meal_meal_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['created']},
        ),
    ]
