# Generated by Django 4.1.3 on 2022-12-10 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_menu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['date', 'created']},
        ),
    ]
