# Generated by Django 4.1.3 on 2022-12-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_menu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_picture',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
