# Generated by Django 4.1.3 on 2022-12-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_meal_meal_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
