# Generated by Django 4.1.3 on 2022-12-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_meal_meal_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['date', 'meal_time', 'created']},
        ),
        migrations.RemoveField(
            model_name='meal',
            name='description_short',
        ),
    ]
